### ISSUE TITLE
获取本地路径问题

### ISSUE THREAD

**Issue by timenews** [ron0115/vscode-image-snippets#16]
习惯写URL()的时候直接写成url("img/xxxx.jpg")
在判断有效连接时能否加上不到./的 case

this.regFilePath = /\.*\w*\/.*\.\w+/;

还有就是能不能把提示添加到默认提示中 而不是替换掉默认提示

谢谢!

**Comment by ron0115** [comment]
@timenews
1. url("img/xxxx.jpg")需要改成截取url()里面的内容，逻辑会与background属性耦合，不考虑修改。

2. 根据目前的vscode版本，在provider中执行`vscode. executeCompletionItemProvider`会有问题，如果有兴趣的话欢迎贡献解决方案。

**Comment by ron0115** [comment]
close
